Repository lblod/frontend-loket, pull requests merged in 2022-09, with the labels that each got.

#176 Adding nationality field in persons component
  app/components/shared/persoon/create-persoon.hbs
  app/components/shared/persoon/create-persoon.js
  app/components/shared/persoon/nationality-selector.hbs
  app/components/shared/persoon/nationality-selector.js
  app/config/custom-inflector-rules.js
  app/models/nationality.js
  app/models/persoon.js
  app/templates/eredienst-mandatenbeheer/new-person.hbs
  app/templates/worship-ministers-management/new-person.hbs
Labels: enhancement

#178 Fix the backend search option of the ConceptSelector component
  app/components/rdf-form-fields/concept-selector.hbs
Labels: bug

#192 Set up release-it
  .release-it.json
  package.json
Labels: internal

#199 Fix a problem on the mandatenbeheer fracties page
  app/components/mandatenbeheer/bestuursperioden-selector.js
  app/controllers/mandatenbeheer/fracties.js
  app/templates/mandatenbeheer/fracties.hbs
Labels: bug

#203 Only serialize the status and modified fields
  app/serializers/public-service.js
  tests/unit/serializers/public-service-test.js
Labels: bug

#205 Only show unique "bestuursorgaan" names
  app/routes/eredienst-mandatenbeheer/mandatarissen.js
  app/templates/eredienst-mandatenbeheer/mandatarissen.hbs
Labels: bug

#207 Fix a scrolling issue on the edit pages of the worship modules
  app/templates/eredienst-mandatenbeheer/mandataris/edit.hbs
  app/templates/worship-ministers-management/minister/edit.hbs
Labels: bug

#208 [Mandatenbeheer] Fixing duplicate bestuursorgaan naam
  app/components/mandatenbeheer/mandataris-table.hbs
  app/models/mandataris.js
  app/routes/eredienst-mandatenbeheer/mandatarissen.js
  app/routes/mandatenbeheer/mandatarissen.js
  app/templates/mandatenbeheer/mandatarissen.hbs
Labels: bug

#209 Fix a problem where creating a public service based on a template no longer worked
  app/serializers/public-service.js
  tests/unit/serializers/public-service-test.js
Labels: bug
