Repository lblod/frontend-loket, pull requests merged in 2023-06, with the labels that each got.

#310 Add support for handling external subsidies
  app/models/subsidy-application-flow-step.js
  app/models/subsidy-measure-offer-series.js
  app/models/subsidy-procedural-step.js
  app/routes/subsidy/applications/available-subsidies.js
  app/routes/subsidy/applications/new.js
  app/templates/subsidy/applications/available-subsidies.hbs
Labels: enhancement

#312 Replace links to the old website with the new equivalents
  app/components/rdf-form-fields/application-form-table/edit.hbs
  app/components/rdf-form-fields/application-form-table/show.hbs
  app/templates/index.hbs
  app/templates/login.hbs
  app/templates/subsidy/applications/available-subsidies-loading.hbs
  app/templates/subsidy/applications/available-subsidies.hbs
  app/templates/subsidy/applications/edit/step/edit.hbs
Labels: enhancement

#313 Don't show the unsaved changes modal for read-only forms
  app/components/public-services/details-page.js
  app/templates/public-services/details/content.hbs
  app/templates/public-services/details/properties.hbs
Labels: bug

#315 Fix the spacing between pills in table rows
  app/components/pill-list.hbs
  app/templates/public-services/add.hbs
  app/templates/public-services/index.hbs
  app/templates/public-services/link-concept/index.hbs
Labels: bug

#316 Don't focus the rich-text editor window when setting the initial value
  app/components/rdf-form-fields/rich-text-editor.js
Labels: bug

#311 Add support for concept archiving
  app/controllers/public-services/concept-details.js
  app/controllers/public-services/details.js
  app/routes/public-services/add.js
  app/routes/public-services/link-concept/index.js
  app/templates/public-services/concept-details.hbs
  app/templates/public-services/details.hbs
Labels: enhancement

#317 Disable the submit and save buttons if the form isn't loaded
  app/components/public-services/details-page.hbs
  app/components/public-services/details-page.js
Labels: bug

#318 Update to ember-promise-modals v4
  package-lock.json
  package.json
Labels: bug

#320 Fix the save and submit buttons
  app/components/public-services/details-page.js
Labels: bug

#321 Update to ember-submission-form-fields v2.11.0
  package-lock.json
  package.json
Labels: dependencies

#319 Add a `lpdc-external` feature flag
  app/components/shared/compact-menu.hbs
  app/components/shared/main-menu.hbs
  app/helpers/lpdc-url.js
  app/router.js
  app/routes/lpdc-external-redirect.js
  app/services/current-session.js
  app/templates/index.hbs
  app/templates/login.hbs
  app/templates/lpdc-external-redirect.hbs
  config/environment.js
Labels: enhancement
