Repository lblod/frontend-loket, pull requests merged in 2023-01, with the labels that each got.

#240 [Bedienarenbeheer / Eredienst-Mandatenbeheer] Allow addresses outside of Flanders
  app/components/contact-information-table.hbs
  app/components/contact-information-table/input-manual-address.hbs
  app/components/contact-information-table/row.hbs
  app/components/contact-information-table/row.js
  app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
  app/controllers/eredienst-mandatenbeheer/new.js
  app/controllers/worship-ministers-management/minister/edit.js
  app/controllers/worship-ministers-management/new.js
  app/models/adres.js
  app/templates/eredienst-mandatenbeheer/mandataris/edit.hbs
  app/templates/eredienst-mandatenbeheer/new.hbs
  app/templates/worship-ministers-management/minister/edit.hbs
  app/templates/worship-ministers-management/new.hbs
Labels: enhancement

#247 [Worship-Modules] Add link to Databank Erediensten
  app/components/shared/compact-menu.hbs
  app/components/shared/main-menu.hbs
  app/helpers/worship-decisions-database-url.js
  app/services/current-session.js
  app/templates/index.hbs
  config/environment.js
Labels: enhancement

#253 LPDC: small delete modal changes
  app/components/public-services/confirm-deletion-modal.hbs
Labels: enhancement

#256 Add a "Conceptual public service" details page
  app/components/public-services/concept-details-page.hbs
  app/components/public-services/concept-details-page.js
  app/components/shared/bread-crumb.js
  app/router.js
  app/routes/public-services.js
  app/routes/public-services/concept-details.js
  app/routes/public-services/concept-details/content.js
  app/routes/public-services/concept-details/index.js
  app/routes/public-services/concept-details/properties.js
  app/routes/public-services/details.js
  app/templates/public-services/concept-details.hbs
  app/templates/public-services/concept-details/content.hbs
  app/templates/public-services/concept-details/properties.hbs
Labels: enhancement

#258 Add a mail link to the helpdesk on the person search pages
  app/components/shared/persoon/persoon-search-result.hbs
  app/components/shared/persoon/persoon-search-result.js
Labels: enhancement

#259 [Worship-modules] Fixing secondaryContactPoint is null error
  app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
  app/controllers/eredienst-mandatenbeheer/new.js
  app/controllers/worship-ministers-management/minister/edit.js
  app/controllers/worship-ministers-management/new.js
Labels: bug

#263 Update most eslint related packages to their latest versions
  package-lock.json
  package.json
Labels: internal

#265 Update to eslint v8
  .eslintrc.js
  app/controllers/mandatenbeheer/mandatarissen.js
  package-lock.json
  package.json
Labels: internal

#254 [Eredienst-mandatenbeheer] View only mode
  app/components/shared/bread-crumb.js
  app/controllers/eredienst-mandatenbeheer/mandatarissen.js
  app/models/bestuurseenheid.js
  app/router.js
  app/routes/eredienst-mandatenbeheer/mandataris/details.js
  app/routes/eredienst-mandatenbeheer/mandataris/edit.js
  app/routes/eredienst-mandatenbeheer/new-person.js
  app/routes/eredienst-mandatenbeheer/new.js
  app/services/current-session.js
  app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
  app/templates/eredienst-mandatenbeheer/mandatarissen.hbs
Labels: enhancement

#255 [Eredienst-bedienarenbeheer] View only mode
  app/components/shared/bread-crumb.js
  app/controllers/worship-ministers-management/index.js
  app/router.js
  app/routes/worship-ministers-management/minister/details.js
  app/routes/worship-ministers-management/minister/edit.js
  app/routes/worship-ministers-management/new-person.js
  app/routes/worship-ministers-management/new.js
  app/services/current-session.js
  app/templates/worship-ministers-management/index.hbs
  app/templates/worship-ministers-management/minister/details.hbs
Labels: enhancement

#261 Allow users to preview a public service concept before creation
  app/components/shared/bread-crumb.js
  app/controllers/public-services/add.js
  app/controllers/public-services/concept-details.js
  app/controllers/public-services/new.js
  app/router.js
  app/routes/public-services/new.js
  app/templates/public-services/add.hbs
  app/templates/public-services/concept-details.hbs
  app/templates/public-services/new.hbs
Labels: enhancement
