Repository lblod/frontend-loket, pull requests merged in 2024-08, with the labels that each got.

#405 [DL-4540, DL-4069] Fix sorting in various places
  app/components/berichtencentrum/conversatie-table.hbs
  app/templates/eredienst-mandatenbeheer/mandatarissen.hbs
  app/templates/supervision/submissions/index.hbs
  app/templates/worship-ministers-management/index.hbs
Labels: bug

#398 [DL-6088] Changes to the overview table in the "Toezicht" module
  app/controllers/supervision/submissions/index.js
  app/templates/supervision/submissions/index.hbs
Labels: enhancement

#406 Update to Ember 5.8 LTS
  .ember-cli
  .eslintignore
  .gitignore
  .prettierignore
  .watchmanconfig
  app/app.js
  app/components/mandatenbeheer/mandataris-summary.js
  app/config/custom-inflector-rules.js
  app/utils/deprecation-workflow.js
  config/ember-cli-update.json
  config/optional-features.json
  package-lock.json
  package.json
  tests/helpers/index.js
Labels: internal

#408 feat: update mandatenbeheer tegels
  README.md
  app/helpers/mandatenbeheer-url.js
  app/services/current-session.js
  app/templates/index.hbs
  config/environment.js
Labels: enhancement
