Repository lblod/frontend-loket, pull requests merged in 2024-05, with the labels that each got.

#384 [DL-5849] Refactor the impersonation feature
  app/components/impersonation-menu.gjs
  app/controllers/application.js
  app/controllers/impersonate.js
  app/services/current-session.js
  app/services/impersonation.js
Labels: enhancement

#385 [DL-5888] Fix the prefill of the fractie-selector component
  app/components/mandatenbeheer/mandataris-edit.js
Labels: bug

#386 [DL-5888] Fix the prefill of the fractie-selector component
  app/components/mandatenbeheer/mandataris-edit.js
Labels: bug

#372 [DGS-161] Add a `subsidies-external` feature flag
  README.md
  app/components/shared/compact-menu.hbs
  app/components/shared/main-menu.hbs
  app/helpers/subsidies-url.js
  app/router.js
  app/routes/subsidies-external-redirect.js
  app/services/current-session.js
  app/templates/index.hbs
  app/templates/subsidies-external-redirect.hbs
  config/environment.js
Labels: enhancement

#388 Resolve `AuLoader` deprecations
  app/components/mandatenbeheer/mandataris-edit.hbs
  app/components/mandatenbeheer/mandatarissen-totals.hbs
  app/components/page-loader.hbs
  app/components/personeelsbeheer/employee-dataset-summary.hbs
  app/components/shared/persoon/persoon-search-form.hbs
  app/templates/loading.hbs
  app/templates/mandatenbeheer/fracties.hbs
  app/templates/mock-login.hbs
  app/templates/subsidy/applications/available-subsidies-loading.hbs
  app/templates/subsidy/applications/edit-loading.hbs
  app/templates/subsidy/applications/edit/step-loading.hbs
  app/templates/subsidy/applications/edit/step/edit-loading.hbs
  app/templates/subsidy/applications/edit/step/new-loading.hbs
  app/templates/subsidy/applications/index-loading.hbs
  app/templates/subsidy/applications/new-loading.hbs
  app/templates/supervision/submissions/edit-loading.hbs
  app/templates/supervision/submissions/new-loading.hbs
Labels: internal
